<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('More Information')) ?></caption>
            <tbody>
            <?php foreach ($_additional as $_data) :?>

<?php
////BEGIN


//echo("<!--value:".$_data['value']."-->");
//echo("<!--code:".$_data['code']."-->");

$replaceValue="";
if($_data['code']=="schedule1") if($_product->getCustomAttribute('schedule1_translated')!==null) $replaceValue=$_product->getCustomAttribute('schedule1_translated')->getValue();
if($_data['code']=="schedule2") if($_product->getCustomAttribute('schedule2_translated')!==null) $replaceValue=$_product->getCustomAttribute('schedule2_translated')->getValue();
if($_data['code']=="address_details") if($_product->getCustomAttribute('address_details_translated')!==null) $replaceValue=$_product->getCustomAttribute('address_details_translated')->getValue();
if($_data['code']=="discount") if($_product->getCustomAttribute('discount_translated')!==null) $replaceValue=$_product->getCustomAttribute('discount_translated')->getValue();




if($replaceValue!="") $_data['value']=$replaceValue;

//echo("<!--value:".$_data['value']."-->");
//echo("<!--code:".$_data['code']."-->");

$attributeHtml=$_helper->productAttribute($_product, $_data['value'], $_data['code']);
/*
Special links with url for:
"facebook" 
"instagram"
"website" 
address -> "google_maps_url"
*/
if($_data['code']=="facebook") $attributeHtml='<a href="https://www.facebook.com/'.$_data['value'].'" target="_blank">'.$_data['value'].'</a>';
if($_data['code']=="instagram") $attributeHtml='<a href="https://www.instagram.com/'.$_data['value'].'/" target="_blank">'.$_data['value'].'</a>';
if($_data['code']=="website") $attributeHtml='<a href="https://'.$_data['value'].'" target="_blank">'.$_data['value'].'</a>';
if($_data['code']=="address") {
    $google_maps_url="";
    if($_product->getCustomAttribute('google_maps_url')!==null) $google_maps_url=$_product->getCustomAttribute('google_maps_url')->getValue();
    if($google_maps_url!="") $attributeHtml='<a href="'.$google_maps_url.'" target="_blank">'.$_data['value'].'</a>';
}
////END
?>

                <tr>
                    <th class="col label" scope="row"><?= $block->escapeHtml($_data['label']) ?></th>
                    <td class="col data" data-th="<?= $block->escapeHtmlAttr($_data['label']) ?>"><?= /* @noEscape */ $attributeHtml ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif;?>
