<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>

<ul class="footer links">
    <li class="nav item"><a href="/bangkok/">Bangkok</a></li>
    <li class="nav item"><a href="/chiangmai/">Chiang Mai</a></li>
    <li class="nav item"><a href="/">Hua Hin</a></li>
    <li class="nav item"><a href="/pattaya/">Pattaya</a></li>
    <li class="nav item"><a href="/phuket/">Phuket</a></li>
</ul>
<ul class="footer links">
    <li class="nav item"><a href="/blog/" title="Saijay Blog"></li>
</ul>

    