<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                    <span><?= $block->escapeHtml($block->getStoreName()) ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown"
                data-target="dropdown">
                <?php 
                    /*
                    $currentWebsite = $this->storeManager->getStore()->getWebsite();

                    // Получите все store view для текущего веб-сайта
                    $storeViews = $currentWebsite->getStoreCollection();
                
                    // Отсортируйте store view по полю "order"
                    $storeViews->setOrder('sort_order', 'ASC');
                    */
                    //if ($_SERVER["HTTP_HOST"] )
                    //if (!in_array($_SERVER["HTTP_HOST"],array("saijay.com","saijay.in"))) 

                ?>
                <?php foreach ($block->getGroups() as $_group) : ?>
                    <?php echo("<!--g:".$_group->getId()."-->"); ?>
                        <?php foreach ($_group->getStores() as $_lang) : ?>
                    
                        <?php echo("<!--l:".$_lang->getCode()."-->"); ?>
                        <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                            <?php echo("<!--ll:".$_lang->getCode()."-->"); ?>

                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>