<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>

<ul class="footer links">
    <li class="nav item"><a href="/bangkok/"><?= $block->escapeHtml(__('Bangkok')) ?></a></li>
    <li class="nav item"><a href="/chiangmai/"><?= $block->escapeHtml(__('Chiang Mai')) ?></a></li>
    <li class="nav item"><a href="/"><?= $block->escapeHtml(__('Hua Hin')) ?></a></li>
    <li class="nav item"><a href="/pattaya/"><?= $block->escapeHtml(__('Pattaya')) ?></a></li>
    <li class="nav item"><a href="/phuket/"><?= $block->escapeHtml(__('Phuket')) ?></a></li>
</ul>

<ul class="footer links">
    <li class="nav item"><a href="https://saijay.com/"><?= $block->escapeHtml(__('Thailand')) ?></a></li>
    <li class="nav item"><a href="https://saijay.us/"><?= $block->escapeHtml(__('USA')) ?></a></li>
    <li class="nav item"><a href="https://saijay.net/"><?= $block->escapeHtml(__('China')) ?></a></li>
    <li class="nav item"><a href="https://saijay.in/"><?= $block->escapeHtml(__('India')) ?></a></li>
    <li class="nav item"><a href="https://saijay.ru/"><?= $block->escapeHtml(__('Russia')) ?></a></li>
</ul>

<ul class="footer links">
    <li class="nav item"><a href="/blog/" title="<?= $block->escapeHtml(__('Saijay Blog')) ?>"><?= $block->escapeHtml(__('Saijay Blog')) ?></a></li>
</ul>
