<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();



$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php
////BEGIN
/*
"subtitle_translated" 
"short_description_translated"
"description_translated"
*/

//echo("<!--code:".$_code."-->");

if($_code=="description")
{
    $use_default=($_product->getData('description')!=false);
    //echo("<!--use_default:".$use_default."-->");
    if($use_default&&($_product->getCustomAttribute('description_translated')!==null))
    {
        //$description_translated=$_helper->productAttribute($_product, $_product->$_call(), "description_translated"); 
        $description_translated=$_product->getCustomAttribute('description_translated')->getValue();

        //$description_translated=$_product->getData('description_translated');
        //echo("<!--description_translated:".$description_translated."-->");    
        if ($description_translated!="") $_attributeValue = $description_translated;
    }
}

if($_code=="short_description")
{
    $use_default=($_product->getData('short_description')!=false);
    //echo("<!--use_default:".$use_default."-->");
    if($use_default&&($_product->getCustomAttribute('short_description_translated')!==null))
    {
        //$short_description_translated=$_helper->productAttribute($_product, $_product->$_call(), "short_description_translated"); //$_product->getData('description_translated');
        $short_description_translated=$_product->getCustomAttribute('short_description_translated')->getValue();
        //echo("<!--short_description_translated:".$short_description_translated."-->");    
        if ($short_description_translated!="") $_attributeValue = $short_description_translated;
    } 
}

if($_code=="sku")
{
    $subtitle="";
    $use_default=($_product->getData('subtitle')!=false);
    if($use_default) {
        if($_product->getCustomAttribute('subtitle_translated')!=null)
        {
            $subtitle=$_product->getCustomAttribute('subtitle_translated')->getValue();
        }
    } else {
        $subtitle=$_product->getCustomAttribute('subtitle')->getValue();
    }

    if($subtitle!=""){
        $renderLabel=false;
        $use_default=($_product->getData('subtitle')!=false);
        //echo("<!--use_default:".$use_default."-->");
        $_attributeValue="<h2>".$subtitle."</h2>";
    }
}

////END
?>

<?php if ($_attributeValue) :?>
<div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
    <?php if ($renderLabel) :?>
        <strong class="type"><?= $block->escapeHtml($_attributeLabel) ?></strong>
    <?php endif; ?>
    <div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>><?= /* @noEscape */ $_attributeValue ?></div>
</div>
<?php endif; ?>
